# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

#services:
#  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  tags:
    - dind
  script:
    - >
        VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]');
        echo "$CI_REGISTRY_IMAGE";
        echo "$CI_REGISTRY_IMAGE:$VERSION";
    # - docker pull "$CI_REGISTRY_IMAGE:$VERSION" || exit 0
    # - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    # - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  tags:
    - dind
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
